---
script: 'rake spec'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
env:
  - PUPPET_VERSION=2.6.11
  - PUPPET_VERSION=3.0.1
  - PUPPET_VERSION=3.2.2
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.11
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.6.11
